# Path to dev
DEV=~/dev

# Path to oh-my-zsh
ZSH=$DEV/robbyrussell/oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="robbyrussell"

# Load my oh-my-zsh customizations
ZSH_CUSTOM=~/.oh-my-zsh/custom

# Enable case sensitive completion
export CASE_SENSITIVE="true"

# add atom as the editor
export EDITOR="atom -w"

# Disable autocorrect
unsetopt correct_all

# Enable rbenv
eval "$(rbenv init -)"

# Enable nodenv
eval "$(nodenv init -)"
plugins=(git ruby)

eval "$(pyenv init -)"

source $ZSH/oh-my-zsh.sh
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"
export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jacobhaff/dev/revops/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/jacobhaff/dev/revops/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jacobhaff/dev/revops/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/jacobhaff/dev/revops/google-cloud-sdk/completion.zsh.inc'; fi
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
