#!/bin/bash
set -e

# Symlink dot/* into home directory as hidden files
for f in $(ls -d ~/.dotfiles/dot/*); do ln -sfn $f ~/.$(basename $f); done

# Symlink files/* into home directory as regular files
for f in $(ls -d ~/.dotfiles/files/*); do ln -sfn $f ~/$(basename $f); done

mkdir -p ~/dev/robbyrussell/oh-my-zsh
cd ~/dev/robbyrussell/oh-my-zsh
if [ -d .git ]; then
  git pull
else
  git clone https://github.com/robbyrussell/oh-my-zsh ~/dev/robbyrussell/oh-my-zsh
fi;
